### ISSUE TITLE
同步出错 提示An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by ghost** [tencentyun/cos_sync_tools_v5#1]
你好，我配置好后运行 `sh start_cos_sync.sh`
结果提示以下错误：
<img width="585" alt="gc1" src="https://user-images.githubusercontent.com/8081759/35222909-8dd55e9a-ffba-11e7-8156-8372ded547ae.png">

操作系统：macOS 10.13.2 
Java: 
```
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

谢谢

**Comment by PixelDust22** [comment]
Same here.

```
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalAccessException: class org.iq80.leveldb.util.ByteBufferSupport cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @543e710e
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.iq80.leveldb.util.ByteBufferSupport.unmap(ByteBufferSupport.java:64)
	at org.iq80.leveldb.impl.MMapLogWriter.unmap(MMapLogWriter.java:226)
	at org.iq80.leveldb.impl.MMapLogWriter.destroyMappedByteBuffer(MMapLogWriter.java:103)
	at org.iq80.leveldb.impl.MMapLogWriter.close(MMapLogWriter.java:79)
	at org.iq80.leveldb.impl.VersionSet.initializeIfNeeded(VersionSet.java:112)
	at org.iq80.leveldb.impl.VersionSet.<init>(VersionSet.java:91)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:178)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:82)
	at com.qcloud.cos_sync_tools_xml.meta.DbRecord.init(DbRecord.java:34)
	at com.qcloud.cos_sync_tools_xml.App.main(App.java:21)
Caused by: java.lang.IllegalAccessException: class org.iq80.leveldb.util.ByteBufferSupport cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @543e710e
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at org.iq80.leveldb.util.ByteBufferSupport.unmap(ByteBufferSupport.java:61)
	... 9 more

```

**Comment by 1a57danc3** [comment]
弄個同步工具還用 JAVA 寫，在下真是佩服！
我 TM 還要去下個 JAVA。。。

**Comment by cloviso** [comment]
哈哈哈哈哈哈  鄙视Java
